name: Deploy to prod channel

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_to_prod:
    runs-on: ubuntu-latest

    env:
      REACT_APP_BASE_URL: "${{ secrets.REACT_APP_BASE_URL }}"
      REACT_APP_POST_PLAYER_NAME: "${{ secrets.REACT_APP_POST_PLAYER_NAME }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build app
        run: yarn build

      - name: Deploy to prod
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: live
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JK2_NAME_EDITOR }}"
          projectId: jk2-name-editor
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
