name: Deploy to live channel

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_to_live:
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_URL: "${{ secrets.REACT_APP_API_URL }}"
      REACT_APP_BASE_URL: "${{ secrets.REACT_APP_BASE_URL }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Enable Corepack
        run: corepack enable

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Deploy to live
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: live
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JK2_NAME_EDITOR }}"
          projectId: jk2-name-editor
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
